import Head from 'next/head';
import { motion as m } from 'framer-motion';
import { item, footerContainer, footerItemContainer } from '../animations';
import Footer from '../src/components/Footer';
import { useEffect, useState } from 'react';

export default function Home() {
   const [scroll, setScroll] = useState<any>()

   useEffect(() => {

    setScroll(window.scrollY)
   
   }, [scroll])
   

   console.log('Test scroll : ', scroll)

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <div className="w-full h-screen">
            <m.div
               initial={{ y: '100%' }}
               animate={{ y: '0%' }}
               exit={{ opacity: 1 }}
               transition={{ duration: 0.5, ease: 'easeOut' }}
               className="bg-orange-100 page_scroll_container">
               <div className="page_content_container">
                  <div className="overflow-hidden">
                     <m.h1
                        animate={{ x: 0 }}
                        initial={{ x: '100%' }}
                        transition={{ duration: 0.5, delay: 0.5 }}
                        className="main_title">
                        Happy Pickle
                     </m.h1>
                  </div>

                  <m.div
                     variants={footerContainer}
                     initial="hidden"
                     animate="show">
                     <div className="overflow-hidden">
                        <m.div
                           variants={footerItemContainer}
                           className="flex justify-between">
                           <div className="overflow-hidden">
                              <div className="overflow-hidden">
                                 <m.h2 variants={item}>Design</m.h2>
                              </div>
                              <div className="overflow-hidden">
                                 <m.h2 variants={item}>company</m.h2>
                              </div>
                              <div className="overflow-hidden">
                                 <m.h2 variants={item}>2022</m.h2>
                              </div>
                           </div>

                           <div className="overflow-hidden">
                              <div className="overflow-hidden">
                                 <m.h3 variants={item}>
                                    This Pickle gonna make you smile.
                                 </m.h3>
                              </div>
                              <div className="overflow-hidden">
                                 <m.h3 variants={item}>
                                    Scottish designs to make you happy.
                                 </m.h3>
                              </div>
                              <div className="overflow-hidden">
                                 <m.h3 variants={item}>
                                    Click contact for cool transition.
                                 </m.h3>
                              </div>
                           </div>
                        </m.div>
                     </div>
                  </m.div>
               </div>
            </m.div>
         </div>

         <Footer />
      </>
   );
}
